# Global Options
splash = false
ipc = on

# The New Wallpaper Block
wallpaper {
    monitor = eDP-1
    path = /home/stark/Pictures/wallpaper.jpg
    fit_mode = cover
}

# Fallback (optional, for other screens)
wallpaper {
    monitor = 
    path = /home/stark/Pictures/wallpaper.jpg
}
