general {
  lock_cmd = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-sessions # use lock-sessions not lock-session for some reason multiple sessions are spawned
}

# [DEBUG] check if `pidof hypridle` checks the pid
# hypridle runs background
listener {
  timeout = 600 # 5 minute idle will trigger on-timeout command
  on-timeout = hyprlock 
}

