# hosts/nixos/default.nix
# Host entry point — imports all modules and defines host-specific settings.
#
# This is the only file referenced by flake.nix. It pulls in everything else.
{ config, pkgs, ... }:

{
  imports = [
    ../../hardware-configuration.nix   # Generated by nixos-generate-config
    ../../modules/boot.nix
    ../../modules/hardware.nix
    ../../modules/desktop.nix
    ../../modules/system.nix
    ../../modules/shell.nix
  ];

  # ─── Home Manager (user-level configs) ─────────────────────────────
  # The `home-manager.nixosModules.home-manager` module itself is added
  # in flake.nix; this just configures it.
  home-manager = {
    useGlobalPkgs = true;   # reuse the system's nixpkgs (no duplicate builds)
    useUserPackages = true; # merge home.packages into the system profile
    # On the FIRST activation home-manager renames existing dotfiles
    # (e.g. ~/.config/hypr) to <name>.backup instead of failing.
    backupFileExtension = "backup";

    users.stark = import ../../home/stark;
  };

  # This value determines the NixOS release your system was originally
  # installed with. DO NOT CHANGE THIS unless you know what you're doing.
  system.stateVersion = "25.05";
}
